[package]
name = "core-challenges"
version = "0.1.0"
edition="2024"

[dependencies]
serde = { workspace = true }
bincode.workspace = true
sha2.workspace = true
hex = { workspace = true }
rayon = { workspace = true }
sysinfo = { workspace = true }

